[package]
name = "dhcache"
version = "0.0.1"
authors = ["Brian Ewell"]
edition = "2021"
description = "A micro Diffie-Hellman parameter generation web-service"
repository = "https://github.com/brianewell/dhcache"
license = "MIT"
#keywords
#categories

[dependencies]
