version: 2
jobs:
  build:
    docker:
      - image: cimg/rust:1.81
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout
      - run: cargo --version
      - run: cargo test
